### ISSUE TITLE
Lien cassé vers la réponse dans st_recherche_fiche.html (404 not found)

### ISSUE THREAD

**Issue by BenoitF16** [ansforge/FIG_ans-ig-PDSm#43]
Dans la page https://interop.esante.gouv.fr/ig/fhir/pdsm/st_recherche_fiche.html, au § 2.5.1.2	Flux 06b : réponse au flux 05-b, le lien sur PDSm_FindDocumentReferencesComprehensiveResponse mène vers un 404 not found.

**Comment by nriss** [comment]
Merci pour ton retour !
pdsm-find-documentreferences-comprehensive-response.html au lieu de https://interop.esante.gouv.fr/ig/fhir/pdsm/StructureDefinition-pdsmfinddocumentreferencescomprehensiveresponse.html
